traefik:
#  variables:
#    CI_DEBUG_TRACE: "true"
    tags:
        - shell, ubuntu, wjlee.myqnapcloud.com
    stage: deploy
    cache:
        paths:
    before_script:
        - set +e # Disable exit on error
        - whoami
        - sudo bash ./scripts/before_script_env.sh
        - sudo mkdir letsencrypt
        - sudo touch $PWD/letsencrypt/acme.json
        - sudo chown -R gitlab-runner:gitlab-runner $PWD/letsencrypt/acme.json
        - sudo chmod 600 $PWD/letsencrypt/acme.json

        - sudo mkdir log
        - sudo touch ./log/access.log
        - sudo chmod 777 ./log/access.log
        - sudo chown -R gitlab-runner:gitlab-runner ./log
        # - sudo bash ./scripts/before_script_install.sh
        - set -e # Enable exit on error 
    script:
        - set +e # Disable exit on error
        - echo $PWD
        # echo " Assume user is gitlab-runner. If root, then sudo can be removed"
        - echo $USER
        - ip route show
        - ifconfig
        - sudo timedatectl set-timezone Asia/Taipei
        - sudo lsb_release -a
        - sudo uname -a
        - sudo netstat -tupln
        - sudo docker --version
        - sudo docker images
        - sudo docker system df
        - sudo docker ps
        - sudo docker container ls -q
        
        # first stop docker process  
        - sudo docker stop  $(sudo docker container ls -aq --filter name=traefik*)
        - sudo docker stop  $(sudo docker container ls -aq --filter name=whoami*)
        - sudo docker stop  $(sudo docker container ls -aq --filter name=yourls*)
        # - sudo docker stop  $(sudo docker container ls -aq --filter name=pages-nginx*)

       # clean up all stop images, containers
        - sudo docker container prune -f
        - sudo docker image prune -a -f

        - sudo docker network create proxy
        - sudo docker network create internal

        # get acme now..
        - sudo curl https://get.acme.sh | sudo sh
        - sudo $HOME/.acme.sh/acme.sh --config-home $PWD/letsencrypt --force --debug --issue -d wjlee.myqnapcloud.com --standalone

        - sudo docker-compose up

        - sudo chown -R gitlab-runner:gitlab-runner $PWD/*
        - sudo chown -R gitlab-runner:gitlab-runner $PWD/letsencrypt/acme.json
        - sudo chmod 600 $PWD/letsencrypt/acme.json
        - set -e # Enable exit on error 