version: '3'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    container_name: traefik
    command:
      - "--metrics.prometheus=true"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - $PWD/letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/acme.json:/acme.json
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name:  whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`wjlee.myqnapcloud.com`)"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"
