version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false
services:
  traefik:
    image: traefik
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8082:8082
    volumes:
      - ./letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./letsencrypt/acme.json:/etc/traefik/acme.json
      - "./configuration/:/configuration/"
      - ./log:/etc/traefik/log
    labels:
      - "traefik.enable=true"
      ### traefik-https =============================================
      - "traefik.http.routers.traefik-https.entrypoints=https"
      - "traefik.http.routers.traefik-https.rule=Host(\"192.168.31.31\") && PathPrefix(\"/traefik\")"

      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=le"
      - "traefik.http.routers.traefik-https.service=traefik"

      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      ### traefik-http ==============================================
      - "traefik.http.routers.traefik-http.entrypoints=http"
      - "traefik.http.routers.traefik-http.rule=Host(\"192.168.31.31\") && PathPrefix(\"/traefik\")"
      
      - "traefik.http.routers.traefik-http.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      ### ===========================================================
      - "traefik.docker.network=proxy"
    networks:
    - proxy
    - internal
  # traefik-forward-auth:
  #   container_name: traefik-forward-auth
  #   image: thomseddon/traefik-forward-auth
  #   ports:
  #     - 4181:4181
  #   environment:
  #     - CLIENT_ID=client_id
  #     - CLIENT_SECRET=client_secret
  #     - SECRET=secret

  #     - AUTH_HOST=auth.sub.domain.com
  #     - COOKIE_DOMAIN=sub.domain.com
  #     - INSECURE_COOKIE=true
  #     - WHITELIST=me@email.com
  #     - LOG_LEVEL=debug
  #   labels:
  #     - traefik.enable=true
  #     - "traefik.http.middlewares.compress=true"
  #     - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #     - 1.0.0.1
  # yourls:
  #   image: yourls
  #   container_name:  yourls
  #   restart: always
  #   ports:
  #     - 8087:80
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.yourls.rule=Host(\"wjlee.myqnapcloud.com/yourls\")
  #     - traefik.http.routers.yourls.entrypoints=https
  #     - traefik.http.services.yourls.loadbalancer.server.port=8087
  #     - traefik.docker.network=proxy
  #     - traefik.docker.network=internal
  #   env_file:
  #     - .env
  # shields:
  #     image: beevelop/shields
  #     container_name: shields      
  #     environment:
  #       INFOSITE: https://wjlee.myqnapcloud.com
  #     restart: always
  # varnish:
  #   image: beevelop/varnish
  #   container_name: varnish     
  #   environment:
  #     VIRTUAL_HOST: https://wjlee.myqnapcloud.com
  #   links:
  #       - "shields:backend"
  #   restart: always