version: '3'

networks:
  proxy:
    external: true
  # internal:
  #   external: false
services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8082:8082
      - 8086:8086
    networks:
      - proxy
    volumes:
      - ./letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme.json
      -  ./access.log:/etc/traefik/log/access.log
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    restart: always
    container_name:  whoami
    ports:
      - 8086:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`wjlee.myqnapcloud.com/whoami`)
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.services.whoami.loadbalancer.server.port=8086
      - traefik.docker.network=proxy
    networks:
      - proxy
  # yourls:
  #   image: yourls
  #   container_name:  yourls
  #   restart: always
  #   ports:
  #     - 8087:80
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.yourls.rule=Host(`wjlee.myqnapcloud.com/yourls`)
  #     - traefik.http.routers.yourls.entrypoints=https
  #     - traefik.http.services.yourls.loadbalancer.server.port=8087
  #     - traefik.docker.network=proxy
  #     - traefik.docker.network=internal
  #   env_file:
  #     - .env
  #   networks:
  #     - proxy
  #     - internal
  # shields:
  #     image: beevelop/shields
  #     container_name: shields      
  #     environment:
  #       INFOSITE: https://wjlee.myqnapcloud.com
  #     restart: always
  # varnish:
  #   image: beevelop/varnish
  #   container_name: varnish     
  #   environment:
  #     VIRTUAL_HOST: https://wjlee.myqnapcloud.com
  #   links:
  #       - "shields:backend"
  #   restart: always