version: '3'

networks:
  proxy:
    external: true
  # internal:
  #   external: false
services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    container_name: traefik
    ports:
      - 80:9080
      - 443:9443
      - 8080:8080
      - 8082:8082
    networks:
      - proxy
    volumes:
      - ./letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./letsencrypt/acme.json:/etc/traefik/acme.json
      - "./configuration/:/configuration/"
      - ./log/access.log:/etc/traefik/log/access.log
    labels:
      - "traefik.enable=true"
      ### traefik ===================================================
      - "traefik.http.routers.traefik-http.entrypoints=http"
      - "traefik.http.routers.traefik-http.rule=Host(`wjlee.myqnapcloud.com`) && PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik-http.middlewares=traefik-https-redirect"

      - "traefik.http.routers.traefik-https.entrypoints=https"
      - "traefik.http.routers.traefik-https.rule=Host(`wjlee.myqnapcloud.com`) && PathPrefix(`/traefik`)"
      #- "traefik.http.routers.traefik-https.middlewares=traefik-auth"

      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=le"
      - "traefik.http.routers.traefik-https.service=traefik"

      #- "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.compress=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      ### metric ===================================================
      - "traefik.http.routers.metrics.rule=Host(`wjlee.myqnapcloud.com`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.metrics.tls=true"
      - "traefik.http.routers.metrics.tls.certResolver=le"
      - "traefik.http.routers.metrics.service=metrics"
      - "traefik.http.services.metrics.loadbalancer.server.port=8082"
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    restart: always
    container_name:  whoami
    ports:
      - 8086:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami-http.entrypoints=http
      - traefik.http.routers.whoami-http.rule=Host(`wjlee.myqnapcloud.com`) && PathPrefix(`/whoami`)
      - traefik.http.routers.whoami-http.middlewares=whoami-https-redirect

      - traefik.http.routers.whoami-https.entrypoints=https
      - traefik.http.routers.whoami-https.rule=Host(`wjlee.myqnapcloud.com`) && PathPrefix(`/whoami`)

      - traefik.http.routers.whoami-https.tls=true
      - traefik.http.routers.whoami-https.tls.certresolver=le
      - traefik.http.routers.whoami-https.service=whoami

      - traefik.http.middlewares.whoami-https-redirect.redirectscheme.scheme=https

      - traefik.http.services.whoami.loadbalancer.server.port=8086
      - traefik.docker.network=proxy
    networks:
      - proxy
  home-nginx:
    image: bitnami/nginx
    restart: always
    container_name: home-nginx
    ports:
      - 9080:80
      - 9443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.home-nginx-http.entrypoints=http
      - traefik.http.routers.home-nginx-http.rule=Host(`wjlee.myqnapcloud.com`)
      - traefik.http.routers.home-nginx-http.middlewares=whoami-https-redirect

      - traefik.http.routers.home-nginx-https.entrypoints=https
      - traefik.http.routers.home-nginx-https.rule=Host(`wjlee.myqnapcloud.com`)

      - traefik.http.routers.home-nginx-https.tls=true
      - traefik.http.routers.home-nginx-https.tls.certresolver=le
      - traefik.http.routers.home-nginx-https.service=home-nginx

      - traefik.http.middlewares.home-nginx-https-redirect.redirectscheme.scheme=https

      - traefik.http.services.home-nginx.loadbalancer.server.port=9080
      - traefik.http.services.home-nginx.loadbalancer.server.port=9443
      - traefik.docker.network=proxy 

  # traefik-forward-auth:
  #   container_name: traefik-forward-auth
  #   image: thomseddon/traefik-forward-auth
  #   ports:
  #     - 4181:4181
  #   environment:
  #     - CLIENT_ID=client_id
  #     - CLIENT_SECRET=client_secret
  #     - SECRET=secret

  #     - AUTH_HOST=auth.sub.domain.com
  #     - COOKIE_DOMAIN=sub.domain.com
  #     - INSECURE_COOKIE=true
  #     - WHITELIST=me@email.com
  #     - LOG_LEVEL=debug
  #   labels:
  #     - traefik.enable=true
  #     - "traefik.http.middlewares.compress=true"
  #     - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #     - 1.0.0.1
  # yourls:
  #   image: yourls
  #   container_name:  yourls
  #   restart: always
  #   ports:
  #     - 8087:80
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.yourls.rule=Host(`wjlee.myqnapcloud.com/yourls`)
  #     - traefik.http.routers.yourls.entrypoints=https
  #     - traefik.http.services.yourls.loadbalancer.server.port=8087
  #     - traefik.docker.network=proxy
  #     - traefik.docker.network=internal
  #   env_file:
  #     - .env
  #   networks:
  #     - proxy
  #     - internal
  # shields:
  #     image: beevelop/shields
  #     container_name: shields      
  #     environment:
  #       INFOSITE: https://wjlee.myqnapcloud.com
  #     restart: always
  # varnish:
  #   image: beevelop/varnish
  #   container_name: varnish     
  #   environment:
  #     VIRTUAL_HOST: https://wjlee.myqnapcloud.com
  #   links:
  #       - "shields:backend"
  #   restart: always